/**
 * EcoPolis: Environmental Questions Database
 * Curated trivia about climate change, renewable energy, conservation, and ecology.
 */

const ENVIRONMENTAL_QUESTIONS = [
  {
    question: "Which greenhouse gas is released in large quantities by livestock farming?",
    options: ["Carbon dioxide (CO2)", "Methane (CH4)", "Nitrous oxide (N2O)", "Water vapor"],
    answer: 1,
    explanation: "Methane (CH4) is a potent greenhouse gas released during livestock digestion (enteric fermentation) and manure management. It is over 25 times more effective at trapping heat than CO2."
  },
  {
    question: "What percentage of the Earth's water is freshwater and accessible for human use?",
    options: ["About 10%", "About 5%", "Less than 1%", "About 25%"],
    answer: 2,
    explanation: "While 70% of Earth is covered in water, 97% is saline ocean water. Of the remaining 3% freshwater, most is locked in glaciers. Less than 1% is easily accessible in lakes, rivers, and aquifers."
  },
  {
    question: "Which source of renewable energy is generated using the natural heat from beneath the Earth's surface?",
    options: ["Geothermal energy", "Hydroelectric energy", "Biomass energy", "Solar thermal energy"],
    answer: 0,
    explanation: "Geothermal energy taps into heat stored in rocks and fluids beneath the Earth's crust, which can be used to generate electricity or heat buildings cleanly."
  },
  {
    question: "What is the primary cause of ocean acidification?",
    options: ["Chemical waste spills", "Absorbing excess carbon dioxide from the atmosphere", "Overfishing", "Rising ocean temperatures"],
    answer: 1,
    explanation: "The oceans absorb roughly 30% of the carbon dioxide emitted into the atmosphere. This reacts with seawater to form carbonic acid, lowering the pH and harming marine life like corals and shellfish."
  },
  {
    question: "Which of the following is considered a 'single-use plastic'?",
    options: ["Tupperware container", "Plastic water bottle cap", "Polystyrene coffee cup", "Nylon backpack"],
    answer: 2,
    explanation: "Polystyrene cups, plastic straws, and grocery bags are single-use plastics designed to be used once and thrown away, often taking hundreds of years to decompose."
  },
  {
    question: "What is the term for a forest that has attained great age without significant disturbance?",
    options: ["Old-growth forest", "Secondary forest", "Planted forest", "Deciduous forest"],
    answer: 0,
    explanation: "Old-growth forests contain unique ecological features, high biodiversity, and massive trees, and store far more carbon than younger, secondary forests."
  },
  {
    question: "How long does a standard plastic bottle take to decompose in a landfill?",
    options: ["10 to 50 years", "Around 100 years", "Around 450 years", "It never decomposes at all"],
    answer: 2,
    explanation: "A standard plastic water bottle (PET) takes about 450 years to decompose in a landfill, breaking down into microplastics that contaminate soil and water."
  },
  {
    question: "What is the main environmental benefit of planting native trees and plants?",
    options: ["They look prettier than exotic ones", "They require less fertilizer and water, and support local biodiversity", "They grow faster than non-native species", "They release oxygen at night instead of the day"],
    answer: 1,
    explanation: "Native plants are adapted to local soils and climates, meaning they need less water and pesticides, and they provide crucial food and habitats for native insects, birds, and wildlife."
  },
  {
    question: "Which energy source generates the most carbon dioxide emissions per unit of energy produced?",
    options: ["Natural Gas", "Nuclear Power", "Coal", "Solar Energy"],
    answer: 2,
    explanation: "Coal is the most carbon-intensive fossil fuel. Burning it releases significantly more CO2 per unit of energy than natural gas, oil, or any renewable energy source."
  },
  {
    question: "What does 'carbon footprint' represent?",
    options: ["The physical mark left by burning coal", "The total greenhouse gas emissions caused by an individual, event, or product", "The depth of carbon deposits in soil", "The efficiency rating of a solar panel"],
    answer: 1,
    explanation: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions, measured in carbon dioxide equivalents (CO2e)."
  },
  {
    question: "Which ecosystem is often referred to as the 'lungs of the planet'?",
    options: ["The Great Barrier Reef", "The Sahara Desert", "The Amazon Rainforest", "The Arctic Tundra"],
    answer: 2,
    explanation: "The Amazon Rainforest produces about 6% of the world's oxygen and acts as a massive carbon sink, absorbing billions of tons of carbon dioxide and playing a vital role in regulating the global climate."
  },
  {
    question: "What is 'fast fashion'?",
    options: ["Clothing designed specifically for athletes", "The rapid production of cheap clothing to meet short-term trends", "Sustainable clothing made from organic materials", "A shipping method for online apparel stores"],
    answer: 1,
    explanation: "Fast fashion relies on low-quality materials and underpaid labor to produce massive amounts of clothing. It leads to huge textile waste, high water usage, and heavy chemical pollution."
  },
  {
    question: "What is the process of restoring water to a clean state after it has been contaminated?",
    options: ["Desalination", "Eutrophication", "Wastewater treatment", "Condensation"],
    answer: 2,
    explanation: "Wastewater treatment removes contaminants from sewage and runoff so the water can be safely returned to the water cycle or reused for agricultural and industrial purposes."
  },
  {
    question: "Which of the following describes 'biodiversity'?",
    options: ["The number of humans living in a city", "The variety of animal and plant life in a particular habitat", "The rate at which plastic is recycled", "The temperature fluctuations in an ecosystem"],
    answer: 1,
    explanation: "Biodiversity is the variety of life on Earth, including genetic diversity, species diversity, and ecosystem diversity. High biodiversity makes ecosystems more resilient."
  },
  {
    question: "What is a 'vampire draw' in energy conservation?",
    options: ["A solar battery storing electricity at night", "Devices consuming electrical power even when turned off but plugged in", "A sudden spike in the power grid during a storm", "A cooling system used in data centers"],
    answer: 1,
    explanation: "Many electronic appliances (TVs, chargers, microwave clocks) draw standby power even when turned off. Unplugging them or using smart power strips eliminates this vampire draw."
  },
  {
    question: "Which international agreement, adopted in 2015, aims to limit global warming to well below 2°C?",
    options: ["The Kyoto Protocol", "The Montreal Protocol", "The Paris Agreement", "The Geneva Convention"],
    answer: 2,
    explanation: "The Paris Agreement is a legally binding international treaty on climate change, signed by 196 parties at COP21, aiming to limit global warming to well below 2 (ideally 1.5) degrees Celsius."
  },
  {
    question: "What happens during 'coral bleaching'?",
    options: ["Corals are painted white to protect them from heat", "Corals expel the algae living in their tissues due to heat stress, turning white", "Ocean currents sweep away dead corals", "Acid rain dissolves the coral reef structures"],
    answer: 1,
    explanation: "When water is too warm, corals expel the symbiotic algae (zooxanthellae) that provide them with food and color. This leaves them white and vulnerable to disease and starvation."
  },
  {
    question: "Which of the following is NOT a fossil fuel?",
    options: ["Coal", "Uranium", "Natural Gas", "Crude Oil"],
    answer: 1,
    explanation: "Uranium is a metal used in nuclear power stations to generate heat through nuclear fission. While nuclear power is non-renewable in a strict sense, uranium is not a fossil fuel."
  },
  {
    question: "What is the 'Albedo effect'?",
    options: ["The increase of tide levels due to the moon", "The ability of surfaces to reflect solar energy back into space", "The absorption of carbon by oceans", "The decomposition rate of organic waste"],
    answer: 1,
    explanation: "Albedo measures how reflective a surface is. Ice and snow have high albedo (reflecting heat), while dark oceans and land have low albedo (absorbing heat). Melting ice reduces the Earth's albedo, warming it faster."
  },
  {
    question: "What is the main environmental issue associated with landfills?",
    options: ["They release methane gas and toxic chemicals (leachate) into groundwater", "They consume too much electricity", "They cause local earthquakes", "They reduce the amount of oxygen in the air"],
    answer: 0,
    explanation: "Decomposing organic waste in oxygen-poor landfills produces methane gas, a strong greenhouse gas. Rainwater also filters through the trash, forming toxic 'leachate' that can contaminate groundwater."
  },
  {
    question: "Which animal is critical for pollinating roughly 35% of global food crops?",
    options: ["Ladybugs", "Bees", "Earthworms", "Mosquitoes"],
    answer: 1,
    explanation: "Bees, butterflies, bats, and birds pollinate plants. Bees are the most vital agricultural pollinators, supporting the growth of fruits, vegetables, and nuts that feed billions."
  },
  {
    question: "What does 'E-waste' refer to?",
    options: ["Eco-friendly organic waste", "Electronic waste like discarded computers, TVs, and phones", "Emissions from cargo ships", "Electric vehicle battery waste only"],
    answer: 1,
    explanation: "E-waste (Electronic waste) contains valuable metals like gold and copper, but also highly toxic substances like lead, mercury, and cadmium, requiring specialized recycling."
  },
  {
    question: "Which of the following represents a circular economy?",
    options: ["Buying products, using them, and throwing them away", "Designing products to be repaired, reused, remanufactured, and recycled", "Exporting waste to other countries", "Relying entirely on coal for energy"],
    answer: 1,
    explanation: "A circular economy aims to eliminate waste and pollution by keeping products, components, and materials in use for as long as possible, rather than discarding them."
  },
  {
    question: "What causes 'dead zones' in oceans and lakes?",
    options: ["Too much plastic blocking the sun", "Low oxygen levels caused by nutrient pollution (fertilizer runoff)", "Underwater volcano eruptions", "Overcrowding of marine mammals"],
    answer: 1,
    explanation: "Agricultural runoff containing nitrogen and phosphorus fuels massive algae blooms. When the algae die and decompose, the process consumes oxygen, creating hypoxic zones where fish cannot survive."
  },
  {
    question: "What is the primary benefit of organic farming?",
    options: ["It produces larger fruits and vegetables", "It avoids synthetic fertilizers and pesticides, preserving soil health", "It requires no water", "It is always cheaper for consumers"],
    answer: 1,
    explanation: "Organic farming relies on crop rotation, composting, and biological pest control. It avoids synthetic chemicals, which prevents chemical runoff and keeps soil ecosystems healthy and fertile."
  },
  {
    question: "Which type of bulb is the most energy-efficient for lighting homes?",
    options: ["Incandescent bulb", "Halogen bulb", "LED (Light Emitting Diode)", "CFL (Compact Fluorescent Lamp)"],
    answer: 2,
    explanation: "LED bulbs use up to 80% less energy than traditional incandescent bulbs and last up to 25 times longer, saving substantial electricity and reducing carbon emissions."
  },
  {
    question: "What is 'reforestation'?",
    options: ["Cutting down trees to make paper", "Planting trees in an area where there was previously a forest", "Converting forests into farmland", "Genetically modifying trees to grow bigger leaves"],
    answer: 1,
    explanation: "Reforestation restores depleted forests, rebuilding habitats, improving water cycles, and capturing carbon dioxide from the atmosphere to combat global warming."
  },
  {
    question: "What is the main environmental risk of offshore oil drilling?",
    options: ["Causing high ocean tides", "Potential oil spills that devastate marine life and coastal habitats", "Depleting the atmosphere's oxygen", "Creating artificial coral reefs"],
    answer: 1,
    explanation: "Offshore drilling runs the risk of catastrophic blowouts (like Deepwater Horizon), releasing millions of barrels of oil that coat marine life, birds, and coastlines in toxic sludge."
  },
  {
    question: "How do trees help prevent soil erosion?",
    options: ["Their leaves block the wind, and their roots anchor the soil in place", "They absorb all the rain so the soil stays bone dry", "They attract worms that pack the soil tightly", "They shade the soil to prevent it from evaporating"],
    answer: 0,
    explanation: "Tree roots form dense networks that bind soil particles together, while their leaf canopies reduce the impact of heavy rain. This prevents wind and water from washing fertile topsoil away."
  },
  {
    question: "Which of the following is a key contributor to urban air pollution (smog)?",
    options: ["Solar panel reflection", "Vehicle exhaust emissions and industrial combustion", "Water vapor from cooling towers", "Wind turbines stirring up dust"],
    answer: 1,
    explanation: "Vehicle exhaust (releasing nitrogen oxides and VOCs) combined with sunlight creates ground-level ozone and particulate matter, forming harmful smog in cities."
  },
  {
    question: "What does 'sustainability' mean?",
    options: ["Maximizing resource extraction to grow the economy as fast as possible", "Meeting current needs without compromising the ability of future generations to meet theirs", "Conserving energy by shutting down all factories", "Using only plastic materials because they last forever"],
    answer: 1,
    explanation: "Sustainability balances environmental health, social equity, and economic viability, ensuring we use Earth's resources at a rate they can naturally regenerate."
  },
  {
    question: "Why are wetlands ecologically important?",
    options: ["They are great places to build commercial shopping malls", "They filter pollutants from water, control floods, and host rich biodiversity", "They produce large amounts of salt", "They prevent trees from growing too tall"],
    answer: 1,
    explanation: "Wetlands act as natural water purifiers, absorbing sediments and pollutants. They also act as giant sponges that absorb floodwaters and provide habitats for thousands of species."
  },
  {
    question: "Which layer of the atmosphere protects Earth from harmful ultraviolet (UV) radiation?",
    options: ["Troposphere", "Mesosphere", "Ozone layer", "Thermosphere"],
    answer: 2,
    explanation: "The ozone layer (located in the stratosphere) absorbs 97-99% of the Sun's medium-frequency ultraviolet light, protecting life on Earth from skin cancer and crop damage."
  },
  {
    question: "What is the primary driver of global wildlife population declines over the last 50 years?",
    options: ["Natural aging of species", "Habitat loss due to human expansion, agriculture, and logging", "Interspecies competition", "Asteroid dust in the upper atmosphere"],
    answer: 1,
    explanation: "The destruction and fragmentation of forests, grasslands, and wetlands for agriculture, housing, and mining is the leading cause of biodiversity loss worldwide."
  },
  {
    question: "Which sector is globally responsible for the largest share of greenhouse gas emissions?",
    options: ["Aviation and shipping", "Electricity and heat production (burning fossil fuels)", "Residential housing construction", "Waste management and recycling"],
    answer: 1,
    explanation: "Electricity and heat production, which relies heavily on burning coal, gas, and oil, contributes roughly 25% of global greenhouse emissions, followed closely by agriculture/forestry."
  },
  {
    question: "What is 'greywater'?",
    options: ["Water contaminated with toxic chemicals from factories", "Gently used wastewater from sinks, showers, and washing machines", "Water containing human sewage", "Rainwater collected directly from clouds"],
    answer: 1,
    explanation: "Greywater is domestic wastewater (excluding toilet water) that can be safely recycled on-site for garden irrigation and toilet flushing, reducing freshwater consumption."
  },
  {
    question: "What is 'greenwashing'?",
    options: ["Washing plastic containers before putting them in the recycling bin", "Deceptive marketing that portrays a company or product as eco-friendly when it is not", "A chemical process used to clean solar panels", "Planting grass on building roofs"],
    answer: 1,
    explanation: "Greenwashing occurs when a company spends more time and money marketing itself as environmentally friendly than actually implementing practices that reduce its environmental impact."
  },
  {
    question: "Which of the following materials can be recycled infinitely without losing quality?",
    options: ["Paper", "Plastic", "Glass and Aluminum", "Cardboard"],
    answer: 2,
    explanation: "Glass and aluminum can be melted down and recycled indefinitely without any loss in purity or structural integrity. Plastic, however, degrades each time it is recycled."
  },
  {
    question: "What is the main benefit of cover crops in agriculture?",
    options: ["They grow food that can be sold for double the price", "They protect and enrich soil nutrients, preventing erosion during off-seasons", "They block insects from flying into fields", "They keep the soil warm during snowy winters"],
    answer: 1,
    explanation: "Cover crops (like clover or rye) are planted to cover the soil rather than to be harvested. They prevent erosion, suppress weeds, improve soil biology, and lock nitrogen into the soil."
  },
  {
    question: "What is the primary environmental danger of thawing Arctic permafrost?",
    options: ["It will make the oceans less salty, causing ships to sink", "It releases massive amounts of trapped carbon dioxide and methane, accelerating warming", "It will cause global volcanic eruptions", "It will make polar bears migrate to cities"],
    answer: 1,
    explanation: "Permafrost is frozen soil that holds vast amounts of ancient organic matter. As it thaws due to rising temperatures, microbes decompose this material, releasing CO2 and methane, which triggers a feedback loop of more warming."
  }
];
